# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 09:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pincode',
            old_name='pincode',
            new_name='pin_code',
        ),
    ]
