# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0002_auto_20170602_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pincode',
            name='voter',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
